# Generated by Django 3.1.13 on 2021-12-17 14:39

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='amount_approved',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZMW', help_text='Amount approved for the project.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='disbursed_amount_to_date',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZMW', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='expenditure',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='ZMW', help_text='Amount spent on the project to date.', max_digits=14, null=True),
        ),
    ]
