# Generated by Django 3.1.13 on 2021-12-29 01:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0004_auto_20211229_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='comments',
            field=tinymce.models.HTMLField(blank=True, help_text='Comments (If project is complete, has completion certificate been issued, when?).', null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_action_personnel',
            field=tinymce.models.HTMLField(blank=True, help_text='Who will conduct what follow up action items.', null=True),
        ),
    ]
