# Generated by Django 3.1.13 on 2021-12-29 01:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0005_auto_20211229_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=tinymce.models.HTMLField(help_text='Training Outcome notes.', verbose_name='Training Outcome notes. Rich text editing is supported.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='A detailed summary of the program. Rich text edditing is supported.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='focus_area',
            field=tinymce.models.HTMLField(blank=True, help_text='Please describe the focus areas of the project.(if any). Rich text editing is supported', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='precis',
            field=tinymce.models.HTMLField(blank=True, help_text='A detailed summary of the project. Rich text edditing is supported.', null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='address',
            field=tinymce.models.HTMLField(blank=True, help_text='Address details and other information necesarry.', null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='A detailed summary of the Sub Project. Rich text edditing is supported.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='focus_area',
            field=tinymce.models.HTMLField(blank=True, help_text='Please describe the focus areas of the project.(if any). Rich text editing is supported', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='size',
            field=tinymce.models.HTMLField(blank=True, help_text='Size (number of Hectors, SquareMeters, Products etc,).', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='notes',
            field=tinymce.models.HTMLField(help_text='Training notes.', verbose_name='Training notes. Rich text editing is supported.'),
        ),
    ]
