# Generated by Django 3.1.13 on 2021-12-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_beneficiary', '0002_auto_20211229_1132'),
        ('tralard', '0006_auto_20211229_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_comppleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('organizationbeneficiary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_beneficiary.organizationbeneficiary')),
                ('sub_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.subproject')),
            ],
            options={
                'verbose_name': 'PPCR Beneficiary',
                'verbose_name_plural': 'PPCR Beneficiaries',
                'abstract': False,
            },
            bases=('dj_beneficiary.organizationbeneficiary',),
        ),
    ]
