# Generated by Django 3.1.13 on 2021-12-31 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0007_auto_20211231_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the district.', max_length=200, null=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the province.', max_length=200, null=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the ward.', max_length=200, null=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.district')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.province'),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('org_type', models.CharField(choices=[('coorperative', 'Co-orperative'), ('businessfirm', 'Business Firm'), ('Other', 'Other')], max_length=100, verbose_name='Organization Type')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='org_logos')),
                ('total_beneficiaries', models.IntegerField(blank=True, null=True, verbose_name='Total Individual Beneficiary Count')),
                ('total_females', models.IntegerField(blank=True, null=True, verbose_name='Total Female Count')),
                ('total_males', models.IntegerField(blank=True, null=True, verbose_name='Total Male Count')),
                ('total_hhs', models.IntegerField(blank=True, null=True, verbose_name='Total HHs')),
                ('female_hhs', models.IntegerField(blank=True, null=True, verbose_name='Female HHs')),
                ('below_sixteen', models.IntegerField(blank=True, null=True, verbose_name='Below 16 Years Old')),
                ('sixteen_to_thirty', models.IntegerField(blank=True, null=True, verbose_name='16 to 30 Years Old')),
                ('thirty_to_fourty_five', models.IntegerField(blank=True, null=True, verbose_name='30 to 40 Years Old')),
                ('above_fourty_five', models.IntegerField(blank=True, null=True, verbose_name='Above 40 Years Old')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('cell', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location')),
                ('sub_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.subproject')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.ward')),
            ],
            options={
                'verbose_name': 'Beneficiary Organization',
                'verbose_name_plural': 'Beneficiary Organizations',
                'abstract': False,
            },
        ),
    ]
