# Generated by Django 3.1.13 on 2021-12-31 09:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0008_auto_20211231_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='sub_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tralard.subproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tralard.ward'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tralard.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='sub_project',
            field=models.ForeignKey(default=1, help_text='Sub Project to follow up.', on_delete=django.db.models.deletion.PROTECT, to='tralard.subproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='ZMW', help_text='Amount approved for the project.', max_digits=14, verbose_name='Amount Approved'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='currency',
            field=models.CharField(choices=[('ZMK', 'ZMK'), ('USD', 'USD'), ('GBP', 'GBP'), ('EU', 'EU')], default='ZMK', help_text='Currency for the project Fund.', max_length=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tralard.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funddisbursed',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='ZMW', help_text='Amount disbursed for the project.', max_digits=14, verbose_name='Amount Disbursed'),
        ),
        migrations.AlterField(
            model_name='funddisbursed',
            name='currency',
            field=models.CharField(choices=[('ZMK', 'ZMK'), ('USD', 'USD'), ('GBP', 'GBP'), ('EU', 'EU')], default='ZMK', help_text='Currency for the project Fund.', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundexpenditure',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='ZMW', help_text='Amount spent on from disbused funds.', max_digits=14, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='fundexpenditure',
            name='currency',
            field=models.CharField(choices=[('ZMK', 'ZMK'), ('USD', 'USD'), ('GBP', 'GBP'), ('EU', 'EU')], default='ZMK', help_text='Currency for the Expenditure.', max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Program Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tralard.program'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tralard.project'),
        ),
    ]
