# Generated by Django 3.1.13 on 2021-12-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0008_auto_20211231_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='Training Moderator. This is the person supervising and or conducting the training, the name will be used on trainings and any other references. ', null=True, to='tralard.Representative'),
        ),
    ]
