# Generated by Django 3.1.13 on 2021-12-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0008_auto_20211230_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'Fund', 'verbose_name_plural': 'Funds'},
        ),
        migrations.AlterModelOptions(
            name='funddisbursed',
            options={'verbose_name': 'Disbursed Fund', 'verbose_name_plural': 'Disbursed Funds'},
        ),
        migrations.AlterModelOptions(
            name='fundexpenditure',
            options={'verbose_name': 'Expenditure', 'verbose_name_plural': 'Expenditures'},
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
    ]
