# Generated by Django 3.1.13 on 2021-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0010_auto_20211230_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_funding',
            field=models.BooleanField(default=False, help_text='Whether this project has an active funding.'),
        ),
    ]
