# Generated by Django 3.1.13 on 2021-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0010_auto_20211231_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='completed',
            field=models.BooleanField(default=False, help_text='Has this Training schedule been conducted andd completed?'),
        ),
    ]
