# Generated by Django 3.1.13 on 2021-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0011_project_has_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_comppleted',
        ),
        migrations.AddField(
            model_name='training',
            name='completed',
            field=models.BooleanField(default=False, help_text='Has this Training schedule been conducted andd completed?'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(help_text='Title of the Training', max_length=200, verbose_name='Title'),
        ),
    ]
