# Generated by Django 3.1.13 on 2021-12-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0011_auto_20211231_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='notes',
            field=models.TextField(blank=True, help_text='Training notes.', null=True, verbose_name='Training notes. Rich text editing is supported.'),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
