# Generated by Django 3.1.13 on 2021-12-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0010_auto_20211231_1635'),
        ('tralard', '0012_auto_20211231_2156'),
    ]

    operations = [
    ]
