# Generated by Django 3.1.13 on 2021-12-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0010_auto_20220101_0019'),
        ('tralard', '0013_merge_20211231_2332'),
    ]

    operations = [
    ]
