# Generated by Django 3.1.13 on 2022-01-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0014_merge_20220101_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_representative',
            field=models.ForeignKey(blank=True, help_text='Project representative. This name will be used on trainings and any other references. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_representatives', to='tralard.representative'),
        ),
    ]
