# Generated by Django 3.1.13 on 2022-01-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0015_auto_20220101_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.ImageField(blank=True, help_text='A banner image for this project. Most browsers support dragging the image directly on to the "Choose File" button above. The ideal size for your image is 512 x 512 pixels.', upload_to='images/programs'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tralard.program'),
        ),
    ]
