# Generated by Django 3.1.13 on 2022-01-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0017_auto_20220101_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_representative',
            field=models.ForeignKey(blank=True, help_text='Program representative. This name will be used on programs and any other references. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_representatives', to='tralard.representative'),
        ),
        migrations.AddField(
            model_name='representative',
            name='cell',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cell'),
        ),
        migrations.AddField(
            model_name='representative',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='representative',
            name='ward',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.program'),
        ),
    ]
