# Generated by Django 3.1.13 on 2022-01-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0018_auto_20220101_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
