# Generated by Django 3.1.13 on 2022-01-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0021_auto_20220101_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='moderators',
        ),
        migrations.AddField(
            model_name='training',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Training Moderator. This is the person supervising and or conducting the training, the name will be used on trainings and any other references. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tralard.representative'),
        ),
    ]
