# Generated by Django 3.1.13 on 2022-01-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0023_auto_20220104_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
