# Generated by Django 3.1.13 on 2022-01-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0023_auto_20220104_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='project',
        ),
        migrations.AddField(
            model_name='fund',
            name='sub_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tralard.subproject'),
            preserve_default=False,
        ),
    ]
