# Generated by Django 3.1.13 on 2022-01-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0024_auto_20220105_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='focus_area',
            field=models.TextField(blank=True, help_text='Please describe the focus areas of the sub project.(if any). Rich text editing is supported', max_length=10000, null=True),
        ),
    ]
