# Generated by Django 3.1.13 on 2022-01-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0024_auto_20220107_0634'),
        ('tralard', '0024_auto_20220105_2236'),
    ]

    operations = [
    ]
