# Generated by Django 3.1.13 on 2022-01-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0025_auto_20220107_0811'),
        ('tralard', '0025_merge_20220107_0918'),
    ]

    operations = [
    ]
