# Generated by Django 3.1.13 on 2022-01-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0027_profile'),
        ('tralard', '0028_auto_20220110_0245'),
    ]

    operations = [
    ]
