# Generated by Django 3.1.13 on 2022-01-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0030_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this project has been approved yet.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_funding',
            field=models.BooleanField(default=False, help_text='Whether this project has an active funding.', null=True),
        ),
    ]
