# Generated by Django 3.1.13 on 2022-01-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0030_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.district'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this project has been approved yet.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_funding',
            field=models.BooleanField(default=False, help_text='Whether this project has an active funding.', null=True),
        ),
    ]
