# Generated by Django 2.2 on 2022-01-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0031_auto_20220112_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='sub_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tralard.SubProject', verbose_name='SubProject name'),
        ),
    ]
