# Generated by Django 2.2 on 2022-01-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0032_auto_20220113_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(blank=True, help_text='Unit of mearsure of this indicator target e.g Hectres, Kilometers, Number of Farmers.', max_length=200, null=True, verbose_name='Unit of mearsure')),
                ('description', models.TextField(blank=True, help_text='A brief description of this indicator target.', null=True, verbose_name='Description')),
                ('baseline_value', models.CharField(blank=True, help_text='A baseline is data or measurement that is collected prior to the implementation of the project.', max_length=200, null=True, verbose_name='Baseline Value')),
                ('target_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Target')),
                ('actual_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actual')),
                ('start_date', models.DateField(verbose_name='Target start date')),
                ('end_date', models.DateField(verbose_name='Target end date')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tralard.Indicator')),
            ],
        ),
    ]
