# Generated by Django 2.2 on 2022-01-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0032_auto_20220113_1849'),
        ('tralard', '0032_auto_20220117_1521'),
    ]

    operations = [
    ]
