# Generated by Django 2.2 on 2022-01-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0032_auto_20220113_1849'),
        ('tralard', '0031_auto_20220111_1535'),
    ]

    operations = [
    ]
