# Generated by Django 2.2 on 2022-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0033_merge_20220117_2037'),
        ('tralard', '0033_indicatortarget'),
    ]

    operations = [
    ]
