# Generated by Django 2.2 on 2022-01-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0034_merge_20220119_1617'),
        ('tralard', '0033_merge_20220118_1212'),
    ]

    operations = [
    ]
