# Generated by Django 2.2 on 2022-01-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0035_merge_20220120_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='sub_project_status',
            new_name='status',
        ),
    ]
