# Generated by Django 2.2.16 on 2022-01-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0036_auto_20220120_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
