# Generated by Django 2.2.16 on 2022-01-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0037_remove_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatortarget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='indicatortarget',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='indicatortarget',
            name='target_value',
        ),
        migrations.CreateModel(
            name='IndicatorTargetValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Target Year')),
                ('target_value', models.CharField(default=0, max_length=200, verbose_name='Target Value')),
                ('actual_value', models.CharField(default=0, max_length=200, verbose_name='Actual/Achieved Value')),
                ('indicator_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tralard.IndicatorTarget')),
            ],
        ),
    ]
