# Generated by Django 2.2.16 on 2022-01-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0037_remove_profile_slug'),
        ('tralard', '0033_auto_20220119_0915'),
    ]

    operations = [
    ]
