# Generated by Django 2.2.16 on 2022-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0038_auto_20220124_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatortarget',
            name='actual_value',
        ),
        migrations.AlterField(
            model_name='indicatortargetvalue',
            name='actual_value',
            field=models.CharField(default=0, max_length=200, verbose_name='Actual Value'),
        ),
    ]
