# Generated by Django 2.2.16 on 2022-01-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0039_auto_20220124_1851'),
        ('tralard', '0038_auto_20220126_1131'),
    ]

    operations = [
    ]
