# Generated by Django 2.2.16 on 2022-01-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0040_merge_20220127_1005'),
        ('tralard', '0038_merge_20220124_0915'),
    ]

    operations = [
    ]
