# Generated by Django 2.2.16 on 2022-02-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('tralard', '0041_merge_20220128_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tralard.SubProject')),
            ],
        ),
    ]
