# Generated by Django 2.2.16 on 2022-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0042_auto_20220131_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='size_description',
            field=models.TextField(blank=True, help_text='A brief description of the project size, like what the size implies.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Size (number of Hectors, SquareMeters, Products etc).', max_digits=10, null=True),
        ),
    ]
