# Generated by Django 2.2.16 on 2022-02-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0042_fundversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundversion',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.Fund'),
        ),
    ]
