# Generated by Django 2.2.16 on 2022-02-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0043_fundversion_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundversion',
            name='fund',
        ),
    ]
