# Generated by Django 2.2.16 on 2022-02-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0043_auto_20220201_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(default='name', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
