# Generated by Django 2.2.16 on 2022-02-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0043_auto_20220201_1644'),
        ('tralard', '0044_remove_fundversion_fund'),
    ]

    operations = [
    ]
