# Generated by Django 2.2.16 on 2022-02-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0045_merge_20220202_1149'),
        ('tralard', '0044_auto_20220202_1102'),
    ]

    operations = [
    ]
