# Generated by Django 2.2.16 on 2022-02-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0042_subprojectimage'),
        ('tralard', '0045_merge_20220202_1149'),
    ]

    operations = [
    ]
