# Generated by Django 2.2.16 on 2022-02-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0046_merge_20220203_1730'),
        ('tralard', '0046_merge_20220203_1115'),
    ]

    operations = [
    ]
