# Generated by Django 2.2.16 on 2022-02-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0047_merge_20220204_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorunitofmeasure',
            name='data_source',
            field=models.CharField(choices=[('size', 'Sub Project Size'), ('total_beneficiaries', 'Total Beneficiaries'), ('total_females', 'Total Beneficiary Female Count'), ('total_males', 'Total Beneficiary Male Count'), ('total_hhs', 'Total HHS'), ('female_hhs', 'Female HHS'), ('beneficiary_orgs', 'Number of Beneficiary Organizations')], max_length=200, verbose_name='Source of data'),
        ),
        migrations.AlterField(
            model_name='training',
            name='sub_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tralard.SubProject', verbose_name='SubProject'),
        ),
    ]
