# Generated by Django 2.2.16 on 2022-02-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0047_merge_20220204_0020'),
        ('tralard', '0047_merge_20220204_0937'),
    ]

    operations = [
    ]
