# Generated by Django 2.2.16 on 2022-02-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0048_merge_20220207_0709'),
        ('tralard', '0048_auto_20220207_1243'),
        ('tralard', '0048_auto_20220208_1223'),
    ]

    operations = [
    ]
