# Generated by Django 2.2.16 on 2022-02-10 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('tralard', '0049_merge_20220208_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(db_column='img_id', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Identified', 'Identified'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('photos', models.ManyToManyField(blank=True, related_name='progress_statuses', to='tralard.Photo')),
            ],
        ),
        migrations.AlterField(
            model_name='subproject',
            name='approved',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.DeleteModel(
            name='SubProjectImage',
        ),
        migrations.AddField(
            model_name='progressstatus',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tralard.SubProject'),
        ),
    ]
