# Generated by Django 2.2.16 on 2022-02-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tralard', '0049_merge_20220208_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(help_text='Name of this subcomponent.', max_length=255, unique=True)),
                ('approved', models.BooleanField(default=False, help_text='Whether this subcomponent has been approved yet.', null=True)),
                ('has_funding', models.BooleanField(default=False, help_text='Whether this subcomponent has an active funding.', null=True)),
                ('status', models.CharField(blank=True, choices=[('Identified', 'Identified'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50, null=True, verbose_name='SubComponent Status')),
                ('description', models.CharField(blank=True, help_text='A short description for the subcomponent', max_length=500, null=True)),
                ('image_file', models.ImageField(blank=True, help_text='A banner image for this subcomponent. Most browsers support dragging the image directly on to the "Choose File" button above. The ideal size for your image is 512 x 512 pixels.', upload_to='images/subcomponents')),
                ('precis', tinymce.models.HTMLField(blank=True, help_text='A detailed summary of the subcomponent. Rich text edditing is supported.', null=True)),
                ('focus_area', tinymce.models.HTMLField(blank=True, help_text='Please describe the focus areas of the subcomponent.(if any). Rich text editing is supported', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='certification_managers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='focus_area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_funding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='precis',
        ),
        migrations.RemoveField(
            model_name='project',
            name='program',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_funders',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_managers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='training_managers',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='A banner image for this project. Most browsers support dragging the image directly on to the "Choose File" button above. The ideal size for your image is 512 x 512 pixels.', upload_to='images/projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='started',
            field=models.DateField(blank=True, null=True, verbose_name='project Start Date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='Feedback Moderator. This name will be used on subcomponent feedback and any other references. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this project has been approved yet.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='A detailed summary of the project. Rich text edditing is supported.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_representative',
            field=models.ForeignKey(blank=True, help_text='project representative. This name will be used on projects and any other references. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_representatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='representative',
            name='address',
            field=tinymce.models.HTMLField(blank=True, help_text='Address details and other information necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='indicator_related_subprojects', to='tralard.Indicator'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tralard.Project'),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='representative',
            field=models.ForeignKey(blank=True, help_text='The Supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subcomponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tralard.SubComponent'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='subcomponent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tralard.SubComponent'),
        ),
    ]
