# Generated by Django 2.2.16 on 2022-02-10 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0050_auto_20220210_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressstatus',
            options={'verbose_name': 'Progress Status', 'verbose_name_plural': 'Progress Statuses'},
        ),
        migrations.AlterField(
            model_name='progressstatus',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
