# Generated by Django 2.2.16 on 2022-02-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0051_auto_20220210_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressstatus',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='progress_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tralard.ProgressStatus'),
        ),
    ]
