# Generated by Django 2.2.16 on 2022-02-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0051_auto_20220210_0940'),
        ('tralard', '0050_auto_20220210_1032'),
    ]

    operations = [
    ]
