# Generated by Django 2.2.16 on 2022-02-14 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0052_auto_20220214_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressstatus',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
