# Generated by Django 2.2.16 on 2022-02-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0052_merge_20220210_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='image_file',
            field=models.ImageField(blank=True, help_text='A banner image for this Sub Project. Most browsers support dragging the image directly on to the "Choose File" button above. The ideal size for your image is 512 x 512 pixels.', upload_to='images/subcomponents'),
        ),
    ]
