# Generated by Django 2.2.16 on 2022-02-14 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0053_progressstatus_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressstatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
