# Generated by Django 2.2.16 on 2022-02-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0053_auto_20220211_0934'),
        ('tralard', '0053_auto_20220211_1337'),
    ]

    operations = [
    ]
