# Generated by Django 2.2.16 on 2022-02-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0054_merge_20220214_1448'),
        ('tralard', '0054_merge_20220214_1100'),
    ]

    operations = [
    ]
