# Generated by Django 2.2.16 on 2022-02-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0054_merge_20220214_1100'),
        ('tralard', '0054_auto_20220214_1553'),
    ]

    operations = [
    ]
