# Generated by Django 2.2.16 on 2022-02-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0055_merge_20220214_1518'),
        ('tralard', '0055_merge_20220216_1246'),
    ]

    operations = [
    ]
