# Generated by Django 2.2.16 on 2022-03-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0056_merge_20220216_1640'),
        ('tralard', '0056_merge_20220217_1048'),
    ]

    operations = [
    ]
