# Generated by Django 2.2.16 on 2022-05-18 09:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0057_merge_20220301_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='precis',
            field=tinymce.models.HTMLField(blank=True, help_text='A detailed summary of the subcomponent. Rich text edditing is supported.', null=True, verbose_name='Precise Summary'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Capture project data in quantity i.e. 2, 3.7, 159.44', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='size_description',
            field=models.TextField(blank=True, help_text='A brief description of the project size i.e. 24 Hectors of Land', max_length=500, null=True),
        ),
    ]
