# Generated by Django 2.2.16 on 2022-05-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tralard', '0058_auto_20220518_1110'),
        ('tralard', '0058_auto_20220516_1614'),
    ]

    operations = [
    ]
