# Generated by Django 3.1.13 on 2021-12-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funding',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SubProject',
        ),
    ]
