# -*- coding: utf-8 -*-
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from tralard.views.beneficiary import (
    beneficiary_detail,
    beneficiary_update,
    beneficiary_delete,
    BeneficiaryOrgListView,
)
from tralard.views.dashboard import HomeTemplateView
from tralard.views.fund import (
    fund_detail,
    update_fund,
    fund_delete,
    delete_disbursement,
    update_disbursement,
    FundListAndCreateView,
    get_disbursement_expenditures,
)
from tralard.views.indicator import (
    poll_state,
    indicator_report,
    create_indicator,
    update_indicator,
    delete_indicator,
    create_indicator_target,
    update_indicator_target,
    create_indicator_target_value,
    update_indicator_target_value,
    create_indicator_unit_of_measure,
    update_indicator_unit_of_measure
)
from tralard.views.map import MapTemplateView
from tralard.views.profile import user_profile_update
from tralard.views.subcomponent import (
    edit_feedback,
    subcomponent_update,
    subcomponent_create,
    subcomponent_delete,
    create_feedback,
    delete_feedback,
    SubComponentDetailView,
    delete_sub_project,
    update_sub_project,
)
from tralard.views.sub_project import (
    progress_status_detail,
    sub_project_update,
    SubProjectDetailView,
    file_upload_view,
    fund_approval_view,
    subproject_fund_delete,
    subproject_fund_detail,
    update_sub_project_fund,
    SubProjectTrainingListView,
    sub_project_training_delete,
    sub_project_training_update,
    SubProjectFundListAndCreateView,
    SubProjectBeneficiaryOrgListView,
    subproject_fund_disbursement_create,
    subproject_disbursement_expenditure_create
)
from tralard.views.training import (
    training_update,
    training_delete,
    TrainingListView,
)
from tralard.views.project import (
    ProjectDetailView, 
    preview_indicator_document,
)
app_name = "tralard"
urlpatterns = [
    # -------- dashboard --------
    path(
        "",
        HomeTemplateView.as_view(),
        name="home",
    ),
    path(
        "map/",
        MapTemplateView.as_view(),
        name="map",
    ),
    # -------- Indicator report download --------
    path(
        "report/<slug:project_slug>/indicators_report/preview_report/",
        preview_indicator_document,
        name="preview_indicator_report",
    ),
    path(
        "report/<slug:project_slug>/indicators_report/",
        indicator_report,
        name="indicators_report_download",
    ),
    path(
        "report/indicators_report/<str:task_id>",
        poll_state,
        name="poll_state",
    ),
    # -------- Project -----------
    path(
        "project/<slug:project_slug>/detail/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_name",
        create_indicator,
        name="indicator-name",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_name/<slug:indicator_slug>/update",
        update_indicator,
        name="indicator-name-update",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_name/<slug:indicator_slug>/delete",
        delete_indicator,
        name="indicator-name-delete",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_target",
        create_indicator_target,
        name="indicator-target",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_target/<int:target_id>/update",
        update_indicator_target,
        name="indicator-target-update",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_target_value",
        create_indicator_target_value,
        name="indicator-target-value",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_target_value/<int:indicator_target_value_id>/update",
        update_indicator_target_value,
        name="indicator-target-value-update",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_target_unit",
        create_indicator_unit_of_measure,
        name="indicator-target-unit",
    ),
    path(
        "project/<slug:project_slug>/detail/indicator_target_unit/<int:indicator_target_unit_id>/update",
        update_indicator_unit_of_measure,
        name="indicator-target-unit-update",
    ),
    # -------- user profile --------
    path(
        "user/profile/update/",
        user_profile_update,
        name="profile-update",
    ),
    # -------- project paths --------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/detail/",
        SubComponentDetailView.as_view(),
        name="subcomponent-detail",
    ),
    path("project/<slug:project_slug>/subcomponent/", subcomponent_create, name="subcomponent"),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/update",
        subcomponent_update,
        name="subcomponent-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/delete",
        subcomponent_delete,
        name="subcomponent-delete",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/sub_project/<slug:sub_project_slug>/delete/",
        delete_sub_project,
        name="sub-project-delete",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/sub_project/<slug:sub_project_slug>/update/",
        update_sub_project,
        name="sub-project-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/feedback/",
        create_feedback,
        name="feedback",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/detail/<slug:feedback_slug>/",
        edit_feedback,
        name="update-feedback",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/delete/<slug:feedback_slug>/",
        delete_feedback,
        name="delete-feedback",
    ),
    # -------- subcomponent fund --------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/fund/",
        FundListAndCreateView.as_view(),
        name="fund-list",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/funds/<slug:fund_slug>",
        update_fund,
        name="fund-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/fund/<slug:fund_slug>/detail/",
        fund_detail,
        name="fund-detail",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/fund/<slug:fund_slug>/delete/",
        fund_delete,
        name="fund-delete",
    ),
    # -------- disbursement --------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/funds/<slug:fund_slug>/disbursements/<slug:disbursement_slug>/delete/",
        delete_disbursement,
        name="disbursement-delete",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/funds/<slug:fund_slug>/disbursements/<slug:disbursement_slug>/update/",
        update_disbursement,
        name="disbursement-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/fund/<slug:fund_slug>/disbursement/<slug:disbursement_slug>/expenditure/",
        get_disbursement_expenditures,
        name="disbursement-expenditure",
    ),
    # -------- subcomponent beneficiary --------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/beneficiary/list/",
        BeneficiaryOrgListView.as_view(),
        name="beneficiary-list",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/beneficiary/<slug:beneficiary_slug>/update/",
        beneficiary_update,
        name="beneficiary-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/beneficiary/<slug:beneficiary_slug>/delete/",
        beneficiary_delete,
        name="beneficiary-delete",
    ),
    # -------- sub project beneficiary --------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/beneficiary/",
        SubProjectBeneficiaryOrgListView.as_view(),
        name="subproject-beneficiary",
    ),
    # -------- training ------------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/training/list/",
        TrainingListView.as_view(),
        name="training-list",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/training/<slug:training_entry_slug>/training/delete/",
        training_delete,
        name="training-delete",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/training/<slug:training_entry_slug>/update/",
        training_update,
        name="training-update",
    ),
    # -------- SubProject --------
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/",
        SubProjectDetailView.as_view(),
        name="subproject-manage",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/upload/",
        file_upload_view,
        name="subproject-file-upload",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/training/list/",
        SubProjectTrainingListView.as_view(),
        name="subproject-training",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/training/<slug:training_entry_slug>/delete/",
        sub_project_training_delete,
        name="subproject-training-delete",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/training/<slug:training_entry_slug>/update/",
        sub_project_training_update,
        name="subproject-training-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/",
        SubProjectFundListAndCreateView.as_view(),
        name="subproject-fund-list",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/<slug:fund_slug>/detail/",
        subproject_fund_detail,
        name="subproject-fund-detail",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/<slug:fund_slug>/",
        update_sub_project_fund,
        name="subproject-fund-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/<slug:fund_slug>/delete/",
        subproject_fund_delete,
        name="subproject-fund-delete",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/<slug:fund_slug>/disbursement/",
        subproject_fund_disbursement_create,
        name="subproject-fund-disbursement-create",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/<slug:fund_slug>/disbursement/<slug:disbursement_slug>/",
        subproject_disbursement_expenditure_create,
        name="subproject-fund-disbursement-expenditure-create",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/update/",
        sub_project_update,
        name="subproject-update",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/progress-status/<int:progress_status_id>/detail/",
        progress_status_detail,
        name="progress-status-detail",
    ),
    path(
        "project/<slug:project_slug>/subcomponent/<slug:subcomponent_slug>/subproject/<slug:subproject_slug>/manage/fund/<slug:fund_slug>/approve/",
        fund_approval_view,
        name="subproject-fund-approval"
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)